# https://docs.travis-ci.com/user/languages/android
language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-23.0.2
    - android-23
    - extra

script:
    - ./gradlew library:build
