# https://docs.travis-ci.com/user/languages/android
language: android

jdk:
  - oraclejdk7
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

before_install:
  - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export JAVA_HOME=$JAVA7_HOME

script:
    - ./gradlew library:build
